### PR TITLE
fix: missing multipart tags

### PR DESCRIPTION
**Pull request by pf-lin**

### CODE REVIEW

**Comment by pf-lin** [comment]
@andy89923

**Comment by andy89923** [comment]
Hi @pf-lin ,

Could you provide the screenshot of the spec in description?

**Comment by andy89923** [comment]
Also, the branch name should use `-` instead of `_`.

**Comment by pf-lin** [comment]
@andy89923 Thanks for your advice.
I've fixed it in PR #45.

**Pull request closed without merging**
